### ISSUE TITLE
Undefined index: mediaType in Formats/ActivityStreams.php

### ISSUE THREAD

**Issue by janboddez** [aaronpk/XRay#104]
Ran into a problem trying to parse https://jlelse.blog/index.xml, which coincidentally gets recognized as Activity Streams as well. http://xray.p3k.io/parse?url=https%3A%2F%2Fjlelse.blog%2Findex.xml&pretty=true seems to choke, too.
```
[2021-03-19 00:00:05] production.ERROR: Undefined index: mediaType {"exception":"[object] (ErrorException(code: 0): Undefined index: mediaType at /<...>/XRay/lib/XRay/Formats/ActivityStreams.php:135)
```
Easy workaround: https://github.com/janboddez/XRay/commit/6b37fca9fd9ae4d233c9dbe4387423cbeace4165

**Comment by janboddez** [comment]
Possibly related to the little AS side note there: https://github.com/aaronpk/XRay/issues/101

**Comment by aaronpk** [comment]
I'm not seeing this error anymore, did your feed change?
