### ISSUE TITLE
odd choice of h-entry from http://mention-tech.appspot.com/

### ISSUE THREAD

**Issue by kevinmarks** [aaronpk/XRay#11]
it picks a random looking h-entry from the page:

{"data":{"type":"entry","url":"http://mention-tech.appspot.com/","published":"2015-12-04 03:21:11.757430","name":"3 months agobrid-gy.appspot.com/post/twitter/mention_tech/672616354978119680 mentioned mention-tech.appspot.com/ \u2705 3 months ago","author":{"type":"card","name":"brid-gy.appspot.com/post/twitter/mention_tech/672616354978119680","url":"https://brid-gy.appspot.com/post/twitter/mention_tech/672616354978119680","photo":null}}}

**Comment by aaronpk** [comment]
There's an h-entry on the page with a URL of http://mention-tech.appspot.com/

If you look at the HTTP headers returned by XRay, you'll actually see an explanation of how it found the item returned.

In this case it says: 

```
X-Parse-Debug: mf2:1: Recognized http://mention-tech.appspot.com/ as an h-entry because an h-entry on the page matched the URL of the request
```
