### ISSUE TITLE
Provided HTML not being used with twitter.com URLs

### ISSUE THREAD

**Issue by barnabywalters** [aaronpk/XRay#114]
When trying to parse a twitter.com URL with custom HTML (in this case from granary.io to add mf2 markup), the provided HTML is ignored and the twitter fetcher is used, despite no API keys being provided to the XRay object.

```php
$xray->parse('https://twitter.com/example/statuses/123456789', '<div class="h-entry">•••');
```

It’s a bit of an edge case, but it’d be nice if XRay would always parse from the provided HTML if it’s present, especially if the fetcher which takes over (in this case twitter) isn’t able to make API requests due to no twitter API keys being provided.

**Comment by aaronpk** [comment]
dropping twitter support in the next release
