### ISSUE TITLE
XRay should follow redirects with brid.gy URLs

### ISSUE THREAD

**Issue by osak** [aaronpk/XRay#118]
Bridgy Fed yields webmention source URL which immediately redirects to the canonical URL in some cases. For example, it yielded https://ap.brid.gy/convert/web/https:/social.mikutter.hachune.net/users/osa_k/statuses/110841748303822746/activity for a reply to a post. This URL redirects to https://ap.brid.gy/convert/web/https://social.mikutter.hachune.net/users/osa_k/statuses/110841748303822746. However, XRay is refusing to follow redirects with brid.gy URLs (along with some other domains) as below.

https://github.com/aaronpk/XRay/blob/438430ffc20e02790f67c19b5d080401fc5bc697/lib/helpers.php#L42-L49

It prevents webmention.io from correctly populating Bridgy Fed replies. As it doesn't look like there is a good reason to refuse redirects from `brid.gy`, this domain should be removed from the rejection list.

**Comment by snarfed** [comment]
As far as I can tell, this is probably the root cause of many of these bugs filed against webmention.io over the last couple years: https://github.com/aaronpk/webmention.io/issues
