### ISSUE TITLE
Parse Tweets

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/XRay#18]
* [x] Tweet text
* [x] Include Photos
* [x] Remove photo URL from tweet text
* [x] Videos
* [x] Quoted tweets should include an h-cite
* [x] RTs should show the person who RT'd as the author and include an h-cite
* [x] Hashtags in the tweet should show up as categories
* [x] Expand all URLs (no t.co URLs in the result)
* [x] Geo content
* [x] user profiles
  * [x] name, nickname, url, photo
  * [x] location

**Comment by snarfed** [comment]
feel free to borrow any of granary's logic: https://github.com/snarfed/granary/blob/master/granary/twitter.py

notably:
* [translating a tweet](https://github.com/snarfed/granary/blob/7a11a3dbbd7e4907b41401dc838ab8f961b78b4d/granary/twitter.py#L979). lots of details, but pretty straightforward.
* [fetching full reply chain.](https://github.com/snarfed/granary/blob/7a11a3dbbd7e4907b41401dc838ab8f961b78b4d/granary/twitter.py#L372) nontrivial, you have to do manual recursive search. :(
* [favorites.](https://github.com/snarfed/granary/blob/7a11a3dbbd7e4907b41401dc838ab8f961b78b4d/granary/twitter.py#L351) not in the API at all, you have to scrape them from HTML. :'{

**Comment by aaronpk** [comment]
Thanks. I'm going to use the API for this. I've written most of this code before, such as for expanding tweets for Loqi's URL previews, so it shouldn't be too hard. I'm going to leave out reply chains and favorites for now :-)
