### ISSUE TITLE
Release as a phar project

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/XRay#21]

**Comment by cweiske** [comment]
aaronpk, yes, I packaged up several apps as .phar

- https://github.com/cweiske/bdrem
- https://github.com/cweiske/phancap
- https://github.com/cweiske/php-sqllint
- https://github.com/cweiske/phorkie

I have build.xml files that use phing's `<pharpackage>` task with a custom stub
this is a very simple stub: https://github.com/cweiske/bdrem/blob/master/src/phar-stub.php
while phorkie has a complicated one, with rewrites: https://github.com/cweiske/phorkie/blob/master/src/stub-phar.php
and expire-headers for static files

**Comment by aaronpk** [comment]
I've decided that since releasing this as a library, being able to run it as a phar project is less important now, so I don't plan on implementing this.
