### ISSUE TITLE
Implement the Post Type Discovery algorithm

### ISSUE THREAD

**Issue by sebsel** [aaronpk/XRay#25]
I don't know if this is the right place, but since I was trying to capture some of php-comments shortcomings, here is a shortcoming of XRay I found :)

> sebsel a thing to note: php-comments gives a 'type' with values like 'reply' and 'like', but XRay just gives 'type=entry' with a 'like-of'. So they do different things.
https://chat.indieweb.org/dev/2017-01-02#t1483372296121000

https://www.w3.org/TR/post-type-discovery/

**Comment by aaronpk** [comment]
XRay's `type` property is meant to represent the Microformats2 vocabulary of the object, rather than the post-type-discovery type of the post. So far I haven't needed a `type=like` property from XRay, do you have a use case for that? I could see adding a new property that indicates that.

**Comment by sebsel** [comment]
Well it's just that php-comments does more than XRay does currently. But that's no good reason.

Thinking about it: yes, I actually use this.
https://indieweb.org/facepile#Sebastiaan_Andeweg

My webmentions are sorted by the type-field from php-comments. (That's how the plugin originally worked.) I use it to display in the facepile, with proper icon, or as a comment below it.

Of course I can write my own logic for it, which I did today to sort my own posts in my indexing database. I had enough of writing checks like that all the time, and creating separate bool fields in my database table. (An entry with a name is an article, but a bookmark with a name is no article.)
The database-example is NOT a use case for XRay though.

Below is my current $page->postType() method (in Kirby), including commented-out things that I don't use, but found on the wiki.

```php
  public function postType() {
    if($this->like_of()->isNotEmpty())     return 'like';
    if($this->bookmark_of()->isNotEmpty()) return 'bookmark';
  //if($this->tag_of()->isNotEmpty())      return 'tag';
    if($this->repost_of()->isNotEmpty())   return 'repost';
    if($this->read_of()->isNotEmpty())     return 'read';  // << haven't implemented myself, now
    if($this->watch_of()->isNotEmpty())    return 'watch'; // << posting as text notes, but I have them!
    if($this->checkin()->isNotEmpty())     return 'checkin';
  //if($this->invitee()->isNotEmpty())     return 'invitation';
    if($this->rsvp()->isNotEmpty())        return 'rsvp';
    if($this->in_reply_to()->isNotEmpty()) return 'reply';
    if($this->template() == 'event')       return 'event';
    if($this->template() == 'review')      return 'review';
    if($this->wrote()->isNotEmpty())       return 'wrote'; // << is one is for myself only :/
    if($this->photo()->isNotEmpty())       return 'photo';
    if($this->name()->isNotEmpty())        return 'article';
    if($this->text()->isNotEmpty())        return 'note'; // << 'text' = 'content'
    return 'entry';
  }
```

Oh, and I totally agree on keeping 'type' for Mf2 :)

**Comment by sebsel** [comment]
New use case! :o

At this moment I display likes as `<3 Seb vindt [dit] leuk.` (Seb likes [this]). I am changing this today by having XRay looking up the liked/bookmarked url. I am going to use the `name` field to replace `[dit]`, but sometimes there is no name for a post.

So I'm now writing checks for wether it's a photo, so I can say 'Seb likes a photo by Aaron Parecki', if the original post was a photo. It would be useful if XRay could do that for me. :)

(still writing my own checks now though... it's also not that hard, so maybe it's okay to do it myself)

**Comment by aaronpk** [comment]
I do think implementing the Post Type Discovery algorithm would be useful. I'll update the issue title accordingly.
