### ISSUE TITLE
Parse h-entry with embedded h-event as 'event'

### ISSUE THREAD

**Issue by sebsel** [aaronpk/XRay#42]
As pointed out by @Zegnat, on the wiki: https://indieweb.org/event#How_to_markup

> Event posts must be marked up with h-event.
> Optionally they can be wrapped in an h-entry as well (though it's not clear this is necessary). Parsers should be prepared to handle events without an h-entry tag.

So, he did: https://licit.li/593fa571d6b80

This shows up as an 'entry' and would be better off as an 'event'.

Simplification of his markup:
```html
    <article class="h-entry">
      <main class="e-content p-name">
        <p class="h-event"> ... </p>
      </main>
    </article>
```

**Comment by aaronpk** [comment]
The fact that the `uid` of that post matches the URL of the page indicates the primary object on the page is the `h-entry`. I don't see any way to parse the `h-event` out of there in a way that makes sense.

**Comment by Zegnat** [comment]
My specific page is a bad example, as the `url` property identifying the `h-event` links to the IndieWeb wiki. Not even sure my page should technically classify as event.

Side note: event is under consideration but not covered by Post Type Discovery yet.

**Comment by aaronpk** [comment]
The wiki has been updated to not recommend nesting the h-event inside an h-entry. https://indieweb.org/wiki/index.php?title=event&diff=37543&oldid=37540 I'm going to close this issue as I don't think this is a valid markup case that needs to be addressed.
