### ISSUE TITLE
Protected tweets as private posts

### ISSUE THREAD

**Issue by sebsel** [aaronpk/XRay#45]
When I fetch a protected tweet / tweet from a private account, there is no indication in XRays result that it is in fact a private post.

Having that information could be useful when displaying [reply contexts](http://indieweb.org/reply-context).

This would also extend to fetching private posts, once we have an automated way of doing that. They would need the same kind of indication.

(Don't need this now, but might be a good thing to keep track of.)

**Comment by gRegorLove** [comment]
I'm running into a situation where I'd need this. My current posting interface uses php-mf2-twitter-shim to pull in the tweet's user object and check the `protected` flag. I'd like to replace that with XRay so would need something similar.

**Comment by aaronpk** [comment]
RIP Twitter
