### ISSUE TITLE
Properly handle h-cite objects

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/XRay#6]
Currently only the "value" property is used for the h-cite object.

Instead, the value of the property (e.g. `in-reply-to`) should be the URL of the h-cite, and there should be a new top-level object, `cite`, which contains the contents of h-cite.

e.g.

```
{
  "data": {
    "type": "entry",
    "name": "This is a reply post",
    "author": ...,
    "in-reply-to": ["http://example.com/100"]
  },
  "cite": { 
    "http://example.com/100": {
      "type": "cite",
      "name": "Example Post",
      "author": {
        "type": "card",
        "name": "Author",
        "url": "http://example.com"
      }
    }
  }
}
```

**Comment by kevinmarks** [comment]
So cite is for all referenced URLs like "urls" in mf2? Is the cite from inline parsing, or fetched from the url itself?

**Comment by aaronpk** [comment]
I was thinking just pulling out the h-cites that are inline. Fetching other linked URLs would be interesting but would potentially slow down the fetch too much. Mostly I am interested in having an easy to consume data structure that doesn't require a lot of if/then checking of types of objects.
