### ISSUE TITLE
Parsing h-feed in minified HTML5 page

### ISSUE THREAD

**Issue by kaushalmodi** [aaronpk/XRay#65]
Hello,

I noticed that you updated php-mf2 on xray and so tried out http://xray.p3k.io/parse?url=https%3A%2F%2Fscripter.co%2F again.

But it is not yet detecting the p-name:

![image](https://user-images.githubusercontent.com/3578197/38123321-7da65944-33a8-11e8-8f92-87ddf3e85784.png)

Should I expect the `p-name` value to show up as `name` element under the `feed` element? Or is the website update pending?

This is the relevant portion of my site source:

```html
<div class="posts h-feed">
  <a class="u-url hide" href=https://scripter.co/></a>
  <a href=https://scripter.co/ class="u-author hide">Kaushal Modi</a>
  <p class="p-name hide">A Scripter&#39;s Notes Homepage
  <article class="summary h-entry">
  <header>
```

---

As a side: The `h-entry` of the first linked page in the h-feed has 2 `in-reply-to`'s, but xray has detected only the first one -- [page][1].

First occurrence:

```html
<div class=reply>In reply to:
  <p>
    <a class="u-in-reply-to h-cite" rel=in-reply-to href=http://www.kevinmarks.com/fragmentions.html>http://www.kevinmarks.com/fragmentions.html</a>
</div>
```

Second occurrence:

```html
<div class=reply>In reply to:
  <p>
    <a class="u-in-reply-to h-cite" rel=in-reply-to href=https://kartikprabhu.com/notes/fragmentioner>https://kartikprabhu.com/notes/fragmentioner</a>
</div>
```

~~*Let me know if I should open a separate issue for this.*~~

---

**Update** (second-half is most likely non-issue)

If I understand correctly, the summary happens to contain only the first in-reply-to, so only that is shown.. the parser hasn't yet jumped into the h-entry.. right?

Thanks!

[1]: https://scripter.co/replies/fragmentions/

**Comment by kaushalmodi** [comment]
I just checked https://pin13.net/mf2/?url=https%3A%2F%2Fscripter.co%2F, and there the h-feed > p-name is detected correctly. 🙌 

![image](https://user-images.githubusercontent.com/3578197/38124269-809f073a-33ae-11e8-91a9-ed551cce6f20.png)

---

So I am guessing that just the xray website update is pending? Sorry for the noise if so.

**Comment by aaronpk** [comment]
Yep your site looks good now! XRay doesn't return the "name" of any feeds right now. Looks good in the raw microformats parsed result though!

**Comment by kaushalmodi** [comment]
Thanks for confirming! Does this issue need to stay open?

**Comment by aaronpk** [comment]
Nope! No problem here!
