### ISSUE TITLE
Instagram multi-posts with videos

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/XRay#84]
Currently Instagram posts with a mix of photos and videos are not handled well, the videos are just dropped. This is mostly due to the fact that there is no clear way to represent this in Microformats, since there is no way to express ordering between `photo` and `video` values.

Here is an example post with a mix of photos and videos: https://www.instagram.com/p/BZWmpecjBwN/

**Comment by swentel** [comment]
I've been thinking about this one the last few days, and I wonder whether it would make sense to store the canonical url of the post into the video property. We'd have to document that clients can't directly use a video player, but are responsible to fetch the URL themselves and parse it, optionally using a call back to the microsub server, as the 'preview' call probably shall return the actual video url.

That would solve it without the microsub server having to do a lot of round trips when importing an instagram feed, although, in the end, that might end up to be more performant.

**Comment by aaronpk** [comment]
This is mostly irrelevant now that it's basically impossible to pull data from Instagram so I'm just going to close it.
