### ISSUE TITLE
Don't choke on invalid dates

### ISSUE THREAD

**Issue by martymcguire** [aaronpk/XRay#89]
This feed: https://every-layout.dev/feed.xml

Advertises itself as an RSS 2.0 feed and loads up fine in a browser. XRay treats it as `unknown` (found via subscribing with Aperture turning up 0 items).

The W3C feed validator [says](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fevery-layout.dev%2Ffeed.xml) the dates in there are invalid, which seems true!

If this is what XRay is tripping on... can XRay be more forgiving?

**Comment by aaronpk** [comment]
So it turns out this feed doesn't start with the normal `<?xml` declaration, which is how XRay was recognizing something as XML. I've added some additional checks for this case.
