### ISSUE TITLE
PHP 7.4 compatibility

### ISSUE THREAD

**Issue by janboddez** [aaronpk/XRay#96]
Certain (but not all) sites would trigger the following error when added to my self-hosted Aperture install:
```
production.ERROR: Trying to access array offset on value of type null {"userId":1,"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at /var/www/html/aperture/vendor/p3k/xray/lib/XRay/Formats/Mf2.php:430
```
Looks like PHP 7.4 no longer supports conditions like `if($content['text'] || $content['html'])` and expects the use of `isset` instead (well, or `array_key_exists()`).

On PHP 7.3, the error doesn't occur.

**Comment by aaronpk** [comment]
Can you provide sample markup that causes this error? It may be an error in XRay or could be a problem with the underlying microformats parser.

**Comment by janboddez** [comment]
It definitely happens when I'm trying to add (the current version, like right now, of) https://social.johanbove.info (a Known site), but again, only on PHP 7.4.

On the front end, the "Save" button spinner keeps spinning endlessly--kind of another, albeit minor, issue--and I get returned a 500 error. Laravel's log file shows the error message above.

It does not happen with, e.g., https://werd.io (Known as well).

I'm choosing microformats for both, by the way.

One difference between both (home)pages is that Ben's contains only (?) articles, while Johan's contains notes, replies and photo posts, too.

_Oh, I'm only now realizing that `$content` is not expected to ever be `null`! So, while wrapping both `$content['text']` and `$content['html']` in `isset()` would maybe suppress **this** error, it's still not the answer ..._

**Comment by aaronpk** [comment]
> Oh, I'm only now realizing that...

Yes exactly, which is why I suspect a bug lower down in the stack. I will take a look at these.

For my reference, I've saved a snapshot of the markup in the page here: https://gist.github.com/aaronpk/e40559e9ebcd6bf36a8ca60f4d4b554c
